### ISSUE TITLE
Should scene really be at the top-level

### ISSUE THREAD

**Issue by wolfv** [jhavl/spatialgeometry#3]
I just noticed that `spatialgeometry` installs `scene.so` directly into the `site-packages` directory, which makes it globally available under `import scene`. 

I think it might be more fitting to place it under `spatialgeometry`? So that the import is `from spatialgeometry import scene`?

**Comment by wolfv** [comment]
PS: we're trying to make a WASM build over here: https://github.com/emscripten-forge/recipes/pull/201

**Comment by jhavl** [comment]
This has been fixed with the latest release
